env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - google
parserOptions:
  ecmaVersion: 12
settings:
  react:
    version: detect
rules:
  max-len: "off"
  indent: [2, 2, { "SwitchCase": 2 }]
  object-curly-spacing: "off"
  space-before-function-paren: "off"
ignorePatterns:
  - node_modules
globals:
  App: True
  fhir: true
  ReactJson: true
  ResultList: true
  SearchPanel: true
